name: Deploy to Platform.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Platform.sh
        run: |
          git remote add platform git@git.ca-1.platform.sh:eawjmbdpw74mi.git
          git push platform main
